
import { Property, PropertyStatus } from './types';

export const PROPERTIES_DATA: Property[] = [
  {
    id: 'prop-001',
    nombre: 'Familia González Pérez',
    direccion: 'Av. Siempre Viva 742, Springfield',
    tipo: 'casa',
    habitaciones: 3,
    banos: 2,
    superficie_m2: 150,
    adeudo_infonavit: 450000,
    adeudo_agua: 1200,
    adeudo_luz: 850,
    adeudo_predial: 3500,
    status: PropertyStatus.Pendiente,
    coordenadas: { lat: 19.4326, lng: -99.1332 },
    comentarios_cliente: null,
  },
  {
    id: 'prop-002',
    nombre: 'Sr. Armando Paredes',
    direccion: 'Calle Falsa 123, Villa Serena',
    tipo: 'departamento',
    habitaciones: 2,
    banos: 1,
    superficie_m2: 85,
    adeudo_infonavit: 280000,
    adeudo_agua: 500,
    adeudo_luz: 300,
    adeudo_predial: 1800,
    status: PropertyStatus.Visitada,
    coordenadas: { lat: 25.6866, lng: -100.3161 },
    comentarios_cliente: 'El departamento está en buenas condiciones generales, pero requiere pintura.',
  },
  {
    id: 'prop-003',
    nombre: 'Lic. Ana Sofía Ramírez',
    direccion: 'Bosques de Chapultepec 5, CDMX',
    tipo: 'casa',
    habitaciones: 4,
    banos: 3,
    superficie_m2: 220,
    adeudo_infonavit: 890000,
    adeudo_agua: 2500,
    adeudo_luz: 1200,
    adeudo_predial: 7800,
    status: PropertyStatus.Viable,
    coordenadas: { lat: 19.420, lng: -99.186 },
    comentarios_cliente: 'Excelente ubicación y potencial. Se confirma viabilidad para inversión.',
  },
  {
    id: 'prop-004',
    nombre: 'Familia Martinez López',
    direccion: 'Río Nilo 234, Guadalajara',
    tipo: 'casa',
    habitaciones: 2,
    banos: 2,
    superficie_m2: 110,
    adeudo_infonavit: 320000,
    adeudo_agua: 900,
    adeudo_luz: 600,
    adeudo_predial: 2100,
    status: PropertyStatus.NoViable,
    coordenadas: { lat: 20.6597, lng: -103.3496 },
    comentarios_cliente: 'Daños estructurales en el techo. No es viable la inversión.',
  },
  {
    id: 'prop-005',
    nombre: 'Ing. Javier Morales',
    direccion: 'Av. Insurgentes Sur 100, Roma Norte',
    tipo: 'departamento',
    habitaciones: 1,
    banos: 1,
    superficie_m2: 60,
    adeudo_infonavit: 150000,
    adeudo_agua: 450,
    adeudo_luz: 250,
    adeudo_predial: 1200,
    status: PropertyStatus.EnRevision,
    coordenadas: { lat: 19.416, lng: -99.160 },
    comentarios_cliente: 'Pendiente de revisar documentación legal.',
  },
  {
    id: 'prop-006',
    nombre: 'Sra. Elena Castillo',
    direccion: 'Paseo de la Reforma 222, Juárez',
    tipo: 'departamento',
    habitaciones: 3,
    banos: 2,
    superficie_m2: 130,
    adeudo_infonavit: 600000,
    adeudo_agua: 1500,
    adeudo_luz: 900,
    adeudo_predial: 4500,
    status: PropertyStatus.Pendiente,
    coordenadas: { lat: 19.435, lng: -99.155 },
    comentarios_cliente: null,
  },
];

export const STATUS_OPTIONS = ["Todos", "Pendiente de visita", "Visitada", "Viable", "No viable", "En revisión"];

export const STATUS_MAP: { [key in PropertyStatus]: { text: string; color: string; badge: string } } = {
  [PropertyStatus.Pendiente]: {
    text: "Pendiente de visita",
    color: "yellow",
    badge: "bg-yellow-100 text-yellow-800",
  },
  [PropertyStatus.Visitada]: {
    text: "Visitada",
    color: "blue",
    badge: "bg-blue-100 text-blue-800",
  },
  [PropertyStatus.Viable]: {
    text: "Viable",
    color: "green",
    badge: "bg-green-100 text-green-800",
  },
  [PropertyStatus.NoViable]: {
    text: "No viable",
    color: "red",
    badge: "bg-red-100 text-red-800",
  },
  [PropertyStatus.EnRevision]: {
    text: "En revisión",
    color: "purple",
    badge: "bg-purple-100 text-purple-800",
  },
};

export const FILTER_TO_STATUS_MAP: { [key: string]: PropertyStatus | 'todos' } = {
    "Todos": "todos",
    "Pendiente de visita": PropertyStatus.Pendiente,
    "Visitada": PropertyStatus.Visitada,
    "Viable": PropertyStatus.Viable,
    "No viable": PropertyStatus.NoViable,
    "En revisión": PropertyStatus.EnRevision
};
